app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::auth();

Route::get('home', 'HomeController@index');

Route::get('post/{id}','AdminPostsController@getPost')->name('post');


Route::group(['middleware'=>'admin'],function(){

    Route::get('/admin', function(){
        return view('admin.index');
    });

    Route::resource('admin/users','AdminUsersController');
    Route::resource('admin/posts','AdminPostsController');
    Route::resource('admin/categories','AdminCategoriesController');
    Route::resource('admin/media','AdminMediaController');
    Route::resource('admin/comments','PostCommentsController');
    Route::resource('admin/comment/replies','CommentRepliesController');
    
});

app/Comment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    //

    protected $fillable = [
        'post_id','is_active','author','email','body'
    ];

    public function post(){
        return $this->belongsTo('App\Post');
    }

    public function replies(){
        return $this->hasMany('App\CommentReply');
    }
}

resources/views/admin/comments/replies/index.blade.php
@extends('layouts.admin')

@section('content')
    <h1>Replies</h1>
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Author</th>
                <th>Post</th>
                <th>Body</th>
                <th>Active</th>
                <th>Delete</th>
                <th>Created at</th>
            </tr>
        </thead>
        <tbody>
            @if (count($replies)>0)
            @foreach ($replies as $reply)
            <tr>
                <td scope="row">{{$reply->id}}</td>
                <td>{{$reply->author}}</td>
                <td><a href="{{route('admin.comments.index',$reply->comment->id)}}">{{$reply->comment->id}}</a></td>
                <td>{{str_limit($reply->body,50)}}</td>
                <td>
                    @if($reply->is_active==1)
                    {!!Form::open(['method'=>'PATCH','action'=>['CommentRepliesController@update',$reply->id]])!!}
                    <input type="hidden" name="is_active" value="0">
                    <div class="form-group">
                        {!! Form::submit('Un approve', ['class'=>'btn btn-info']) !!}
                    </div>
                    {!!Form::close()!!}
                    @else
                    {!!Form::open(['method'=>'PATCH','action'=>['CommentRepliesController@update',$reply->id]])!!}
                    <input type="hidden" name="is_active" value="1">
                    <div class="form-group">
                        {!! Form::submit('Approve', ['class'=>'btn btn-primary']) !!}
                    </div>
                    {!!Form::close()!!}
                    @endif
                </td>
                <td>
                        {!!Form::open(['method'=>'DELETE','action'=>['CommentRepliesController@destroy',$reply->id]])!!}
                        <div class="form-group">
                            {!! Form::submit('Delete', ['class'=>'btn btn-danger']) !!}
                        </div>
                        {!!Form::close()!!}
                </td>
                <td>{{$reply->created_at->diffForHumans()}}</td>
            </tr>
            @endforeach
            @else
            <tr>
                <td colspan="6">No comments found</td>
            </tr>
            @endif
        </tbody>
    </table>
@endsection