app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::auth();

Route::get('home', 'HomeController@index');

Route::get('post/{id}','AdminPostsController@getPost')->name('post');


Route::group(['middleware'=>'admin'],function(){

    Route::get('/admin', function(){
        return view('admin.index');
    });

    Route::resource('admin/users','AdminUsersController');
    Route::resource('admin/posts','AdminPostsController');
    Route::resource('admin/categories','AdminCategoriesController');
    Route::resource('admin/media','AdminMediaController');
    Route::resource('admin/comments','PostCommentsController');
    Route::resource('admin/comment/replies','CommentRepliesController');
    
});

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','role_id','is_active','photo_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function role(){
        return $this->belongsTo('App\Role');
    }

    public function photo(){
        return $this->belongsTo('App\Photo');
    }

    public function posts(){
        return $this->hasMany('App\Post');
    }

    public function isAdmin(){
        if($this->role_id==1){
            return true;
        }else{
            return false;
        }
    }
    
    public function isActive(){
        if($this->is_active==1){
            return true;
        }else{
            return false;
        } 
    }

    public function isAdminAndActive(){
        if($this->isAdmin()&&$this->isActive()){
            return true;
        }else{
            return false;
        } 
    }

    public function getGravatarAttribute(){
        $hash = md5(strtolower(trim($this->attribute['email'])))."?d=mm";
        return "https://www.gravatar.com/avatar/".$hash;
    }
}

resources/views/admin/users/create.blade.php
@extends('layouts.admin')

@section('content')
<h1>Create</h1>
@include('includes.form_error')
{!! Form::open(['method' => 'post','action'=>'AdminUsersController@store','files'=>true]) !!}
<div class="form-group">
    {!! Form::label('name', 'Name:') !!}
    {!! Form::text('name', null,['class'=>'form-control']) !!}
</div>
<div class="form-group">
    {!! Form::label('email', 'Email:') !!}
    {!! Form::text('email', null,['class'=>'form-control']) !!}
</div>
<div class="form-group">
    {!! Form::label('role_id', 'Role:') !!}
    {{-- {!! Form::select('role_id',array(1=>'active',2=>'not active'), null,['class'=>'form-control']) !!} --}}
    {!! Form::select('role_id',$roles, null,['class'=>'form-control']) !!}
</div>
<div class="form-group">
        {!! Form::label('photo_id', 'File:') !!}
        {!! Form::file('photo_id', null,['class'=>'form-control']) !!}
    </div>
<div class="form-group">
    {!! Form::label('password', 'Password:') !!}
    {!! Form::password('password',['class'=>'form-control']) !!}
</div>
<div class="form-group">
    {!! Form::submit('Create User', ['class'=>'btn btn-primary']) !!}
</div>

{!! Form::close() !!}

@endsection

resources/views/admin/users/edit.blade.php
@extends('layouts.admin')

@section('content')
<h1>Edit</h1>
<div class="col-sm-3">
    <img src="{{$user->photo?$user->photo->photo_path:"https://via.placeholder.com/400x400"}}" class="img-responsive img-rounded" alt="">
</div>


<div class="col-sm-9">
    @include('includes.form_error')
    
    {!! Form::model($user,['method' => 'patch','action'=>['AdminUsersController@update',$user->id],'files'=>true]) !!}
    <div class="form-group">
        {!! Form::label('name', 'Name:') !!}
        {!! Form::text('name', null,['class'=>'form-control']) !!}
    </div>
    <div class="form-group">
        {!! Form::label('email', 'Email:') !!}
        {!! Form::text('email', null,['class'=>'form-control']) !!}
    </div>
    <div class="form-group">
        {!! Form::label('role_id', 'Role:') !!}
        {{-- {!! Form::select('role_id',array(1=>'active',2=>'not active'), null,['class'=>'form-control']) !!} --}}
        {!! Form::select('role_id',$roles, null,['class'=>'form-control']) !!}
    </div>
    <div class="form-group">
        {!! Form::label('photo_id', 'File:') !!}
        {!! Form::file('photo_id', null,['class'=>'form-control']) !!}
    </div>
    <div class="form-group">
        {!! Form::label('password', 'Password:') !!}
        {!! Form::password('password',['class'=>'form-control']) !!}
    </div>
    <div class="form-group">
        {!! Form::submit('Edit User', ['class'=>'btn btn-primary']) !!}
    </div>
    
    {!! Form::close() !!}
    
    {!! Form::open(['method' => 'DELETE','action'=>['AdminUsersController@destroy',$user->id]]) !!}

    <div class="form-group">
        {!! Form::submit('Delete User', ['class'=>'btn btn-danger']) !!}
    </div>

    {!! Form::close() !!}
    
</div>
@endsection

resources/views/admin/users/index.blade.php
@extends('layouts.admin')

@section('content')
@if(Session::has('flash_user'))
<div class="alert alert-success">
    <strong>Success!</strong> {{session('flash_user')}}
</div>
@endif

<h1>Users</h1>
<table class="table">
    <thead>
        <tr>
            <th>User Id</th>
            <th>Username</th>
            <th>Image</th>
            <th>email</th>
            <th>Role</th>
            <th>Active</th>
            <th>Created at</th>
            <th>Updated at</th>
        </tr>
    </thead>
    <tbody>
        @if(count($users))
        @foreach ($users as $user)
        <tr>
            <td>{{$user->id}}</td>
            <td><a href="{{route('admin.users.edit',$user->id)}}">{{$user->name}}</a></td>
            <td><img src="{{$user->photo?$user->photo->photo_path:"https://via.placeholder.com/350x150"}}" height="50" alt=""></td>
            <td>{{$user->email}}</td>
            <td>{{$user->role?$user->role->name:"no type"}}</td>
            <td>{{$user->is_active? "Active" : "Not active"}}</td>
            <td>{{$user->created_at->diffForHumans()}}</td>
            <td>{{$user->updated_at->diffForHumans()}}</td>
        </tr>
        @endforeach
        @else
        <tr>
            <td colspan="7" class="table-no-data">
                no users found
            </td>
        </tr>
        
        
        @endif
    </tbody>
</table>
@endsection