app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::auth();

Route::get('home', 'HomeController@index');

Route::get('post/{id}','AdminPostsController@getPost')->name('post');


Route::group(['middleware'=>'admin'],function(){

    Route::get('/admin', function(){
        return view('admin.index');
    });

    Route::resource('admin/users','AdminUsersController');
    Route::resource('admin/posts','AdminPostsController');
    Route::resource('admin/categories','AdminCategoriesController');
    Route::resource('admin/media','AdminMediaController');
    Route::resource('admin/comments','PostCommentsController');
    Route::resource('admin/comment/replies','CommentRepliesController');
    
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    //
    protected $fillable = ['name'];

}

resources/views/admin/categories/create.blade.php
@extends('layouts.admin')

@section('content')
<h1>Create Category</h1>
@include('includes.form_error')
{!! Form::open(['method'=>'post','action'=>'AdminCategoriesController@store']) !!}
    <div class="form-group">
        {!! Form::label('name', 'Name:') !!}
        {!! Form::text('name', null,['class'=>'form-control']) !!}
    </div>
    <div class="form-group">
        {!! Form::submit('Create Category',['class'=>'btn btn-primary']) !!}
    </div>
{!! Form::close() !!}
@endsection

resources/views/admin/categories/edit.blade.php
@extends('layouts.admin')

@section('content')
<h1>Edit Category</h1>
@include('includes.form_error')
{!! Form::model($category,['method'=>'patch','action'=>['AdminCategoriesController@update',$category->id]]) !!}
    <div class="form-group">
        {!! Form::label('name', 'Name:') !!}
        {!! Form::text('name', null,['class'=>'form-control']) !!}
    </div>
    <div class="form-group">
        {!! Form::submit('Edit Category',['class'=>'btn btn-primary']) !!}
    </div>
{!! Form::close() !!}
{!! Form::open(['method'=>'delete','action'=>['AdminCategoriesController@destroy',$category->id]]) !!}
    <div class="form-group">
        {!! Form::submit('Delete Category',['class'=>'btn btn-danger']) !!}
    </div>
{!! Form::close() !!}
@endsection

resources/views/admin/categories/index.blade.php
@extends('layouts.admin')

@section('content')
<h1>Categories</h1>
<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Updated at</th>
            <th>Created at</th>
        </tr>
    </thead>
    <tbody>
        @if (count($categories))
        @foreach ($categories as $category)
        <tr>
            <td scope="row">{{$category->id}}</td>
            <td><a href="{{route('admin.categories.edit',$category->id)}}">{{$category->name}}</a></td>
            <td>{{$category->updated_at->diffForHumans()}}</td>
            <td>{{$category->created_at->diffForHumans()}}</td>
        </tr>
        @endforeach
        @else
            <tr>
                <td colspan="100" class="table-no-data">
                    No categories found
                </td>
            </tr>
        @endif
        
        
    </tbody>
</table>
@endsection